-- MySQL Script generated by MySQL Workbench
-- Tue Dec 11 10:18:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema skolniUkol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema skolniUkol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `skolniUkol` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema configuration
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema configuration
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `configuration` DEFAULT CHARACTER SET utf8 ;
USE `skolniUkol` ;

-- -----------------------------------------------------
-- Table `skolniUkol`.`su_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skolniUkol`.`su_groups` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `skolniUkol`.`su_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skolniUkol`.`su_users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(45) NOT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(254) NOT NULL,
  `activation_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_code` VARCHAR(40) NULL DEFAULT NULL,
  `forgotten_password_time` INT(11) UNSIGNED NULL DEFAULT NULL,
  `remember_code` VARCHAR(40) NULL DEFAULT NULL,
  `created_on` INT(11) UNSIGNED NOT NULL,
  `last_login` INT(11) UNSIGNED NULL DEFAULT NULL,
  `active` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `company` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `su_ci_session` (
  `id` varchar(40) COLLATE utf8_czech_ci NOT NULL,
  `ip_address` varchar(45) COLLATE utf8_czech_ci NOT NULL,
  `timestamp` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `data` blob NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;

-- -----------------------------------------------------
-- Table `skolniUkol`.`su_users_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skolniUkol`.`su_users_groups` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `group_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_groups_users1_idx` (`user_id` ASC),
  INDEX `fk_users_groups_groups1_idx` (`group_id` ASC),
  UNIQUE INDEX `uc_users_groups` (`group_id` ASC),
  CONSTRAINT `fk_users_groups_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `skolniUkol`.`su_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_groups_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `skolniUkol`.`su_groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `skolniUkol`.`su_login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skolniUkol`.`su_login_attempts` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(45) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `time` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `skolniUkol`.`su_znacka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skolniUkol`.`su_znacka` (
  `idZnacka` INT NOT NULL AUTO_INCREMENT,
  `nazevZnacky` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idZnacka`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skolniUkol`.`su_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skolniUkol`.`su_model` (
  `idModel` INT NOT NULL AUTO_INCREMENT,
  `nazevModel` VARCHAR(255) NOT NULL,
  `delete` TINYINT NULL,
  `pic` VARCHAR(255) NOT NULL,
  `karoserie` INT NOT NULL,
  `barva` INT NOT NULL,
  `znacka_idZnacka` INT NOT NULL,
  PRIMARY KEY (`idModel`),
  INDEX `fk_su_model_su_znacka1_idx` (`znacka_idZnacka` ASC),
  CONSTRAINT `fk_su_model_su_znacka1`
    FOREIGN KEY (`znacka_idZnacka`)
    REFERENCES `skolniUkol`.`su_znacka` (`idZnacka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `configuration` ;

-- -----------------------------------------------------
-- Table `configuration`.`vyrobce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `configuration`.`vyrobce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `configuration`.`typKomponentu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `configuration`.`typKomponentu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `configuration`.`komponent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `configuration`.`komponent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NOT NULL,
  `idVyrobce` INT NOT NULL,
  `idTypKomponentu` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_komponent_vyrobce_idx` (`idVyrobce` ASC),
  INDEX `fk_komponent_typKomponentu1_idx` (`idTypKomponentu` ASC),
  CONSTRAINT `fk_komponent_vyrobce`
    FOREIGN KEY (`idVyrobce`)
    REFERENCES `configuration`.`vyrobce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_komponent_typKomponentu1`
    FOREIGN KEY (`idTypKomponentu`)
    REFERENCES `configuration`.`typKomponentu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `configuration`.`jednotka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `configuration`.`jednotka` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `configuration`.`parametr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `configuration`.`parametr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `configuration`.`hodnotyKomponentu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `configuration`.`hodnotyKomponentu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hodnota` INT NOT NULL,
  `idKomponent` INT NOT NULL,
  `idJednotka` INT NOT NULL,
  `idParametr` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hodnotyKomponentu_komponent1_idx` (`idKomponent` ASC),
  INDEX `fk_hodnotyKomponentu_jednotka1_idx` (`idJednotka` ASC),
  INDEX `fk_hodnotyKomponentu_parametr1_idx` (`idParametr` ASC),
  CONSTRAINT `fk_hodnotyKomponentu_komponent1`
    FOREIGN KEY (`idKomponent`)
    REFERENCES `configuration`.`komponent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hodnotyKomponentu_jednotka1`
    FOREIGN KEY (`idJednotka`)
    REFERENCES `configuration`.`jednotka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hodnotyKomponentu_parametr1`
    FOREIGN KEY (`idParametr`)
    REFERENCES `configuration`.`parametr` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
